name: fxd
description: An Adobe XD clone built with flutter.
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ">=2.15.1 <3.0.0"

dependencies:
  bitsdojo_window: ^0.1.1+1
  bloc: ^8.0.2
  cupertino_icons: ^1.0.4
  equatable: ^2.0.3
  flutter:
    sdk: flutter
  flutter_bloc: ^8.0.1
  flutter_localizations:
    sdk: flutter
  flutter_svg: ^1.0.3
  intl: ^0.17.0

dev_dependencies:
  bloc_test: ^9.0.2
  build_runner: ^2.1.7
  flutter_gen_runner: ^4.1.5
  flutter_test:
    sdk: flutter
  mocktail: ^0.2.0

flutter:
  generate: true
  uses-material-design: true
  assets:
    - assets/icons/toolbar/

flutter_gen:
  output: lib/assets/
  integrations:
    flutter_svg: true

