name: uxd
description: An Adobe XD clone built with flutter.
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ">=2.17.0 <3.0.0"

dependencies:
  bitsdojo_window: ^0.1.2
  bloc: ^8.0.3
  cupertino_icons: ^1.0.5
  equatable: ^2.0.3
  flutter:
    sdk: flutter
  flutter_bloc: ^8.0.1
  flutter_localizations:
    sdk: flutter
  flutter_svg: ^1.1.0
  google_fonts: ^3.0.1
  intl: ^0.17.0
  vector_math: ^2.1.2

dev_dependencies:
  bloc_test: ^9.0.3
  build_runner: ^2.1.11
  flutter_gen_runner: ^4.3.0
  flutter_test:
    sdk: flutter
  mocktail: ^0.3.0

flutter:
  generate: true
  uses-material-design: true
  assets:
    - assets/icons/toolbar/

flutter_gen:
  output: lib/assets/
  integrations:
    flutter_svg: true

