name: uxd

on: [ push, pull_request ]

jobs:
  build:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v3
      - uses: subosito/flutter-action@v2

      - name: Install Dependencies
        run: flutter pub get

      - name: Format
        run: flutter format --set-exit-if-changed .

      - name: Analyze
        run: flutter analyze

      - name: Run Tests
        run: |
          dart pub global activate remove_from_coverage
          export PATH=$PATH:$HOME/.pub-cache/bin
          flutter test --no-pub --coverage --test-randomize-ordering-seed random
          dart pub global run remove_from_coverage:remove_from_coverage -f coverage/lcov.info -r '.g.dart$'
          dart pub global run remove_from_coverage:remove_from_coverage -f coverage/lcov.info -r '.confg.dart$'

      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v2
        with:
          token: ${{ secrets.CODECOV_TOKEN }}

      - name: Build Macos App
        run: |
          flutter config --enable-macos-desktop
          flutter build macos --release
